#!/bin/bash

# If the Application Home screen is blank: https://aur.archlinux.org/packages/maya?O=80#comment-871405
# Just add --single-process to the Maya command line to work around the issue.

DEFAULT_WEB_BROWSER="/usr/bin/brave-browser"
LICENSE_HELPER=/opt/Autodesk/AdskLicensing/Current/helper/AdskLicensingInstHelper

if ! "$LICENSE_HELPER" list 2>/dev/null | grep -q '"sel_prod_key"'; then
    echo "[x] Maya is not registered, did you run '/opt/maya-install/first-run.sh'?" >&2

    distrobox-host-exec /usr/bin/notify-send \
        --expire-time 18000 \
        --app-name "Maya in a box" \
        --icon "license" \
"Maya is not registered" \
"The <b>first-run.sh</b> script needs to be run to register the Maya license.
- Inside the container:
<b>$ /opt/maya-install/first-run.sh</b>
- Alternatively, on the host:
<b>$ distrobox enter $CONTAINER_ID -- /opt/maya-install/first-run.sh</b>" 2>/dev/null

    exit 1
fi

export QT_QPA_PLATFORM=xcb
export GDK_BACKEND=x11
export XDG_SESSION_TYPE=x11
export MAYA_DISABLE_ADP=1
export MAYA_DISABLE_CIP=1
export MAYA_DISABLE_CER=1
export BROWSER="$DEFAULT_WEB_BROWSER"
export DISPLAY="${DISPLAY:-:0}"
unset WAYLAND_DISPLAY
unset DESKTOP_SESSION
unset XDG_CURRENT_DESKTOP
unset KDE_FULL_SESSION

exec /usr/autodesk/maya2027/bin/maya2027 "$@"
